package com.example.huntertalk.everythingWithGroups

import android.webkit.JavascriptInterface
import android.webkit.WebView

class VoipLayer(groupID: Int) {
    /**
     * Methods for the javascript running inside voice_webview to interact with the Android app
     */

    val groupID: Int = groupID
    @JavascriptInterface get //add annotation to Kotlin's autogenerated getter

    @JavascriptInterface
    fun onUserStartsTalking() {
        //stub
    }

    @JavascriptInterface
    fun onUserStopsTalking() {
        //stub
    }
}