package com.example.huntertalk.everythingWithGroups

import android.webkit.JavascriptInterface

class VoipLayer(groupID: Int) {
    /**
     * Methods for communication between VoipFragment and the javascript running inside voice_webview
     */

    val groupID: Int = groupID
    @JavascriptInterface get //add annotation to Kotlin's autogenerated getter

    @JavascriptInterface
    fun onUserStartsTalking() {
        //stub
    }

    @JavascriptInterface
    fun onUserStopsTalking() {
        //stub
    }

    fun startTalking() {
        //stub
    }

    fun stopTalking() {
        //stub
    }

}